backend:
  name: github
  repo: dionizh/gatsby-netlify

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "" }
      - { label: "Featured Image", name: "thumbnail", widget: "image"} 
      - { label: "Body", name: "body", widget: "markdown" }
